[package]
#todo change authors
authors = ["Timo Renk <timo.renk@stud.uni-bamberg.de>"]
edition = "2021"
name = "user_1"
version = "0.1.0"

[dependencies]
riscv_utils = {path = "../riscv"}
user_shared = {path = "../user_shared"}

[[bin]]
name = "user_1"
path = "src/user_1.rs"
